---
- hosts: all
  become: yes
  environment:
    EXTERNAL_URL: "http://localhost"
  tasks:
  - name: install required packages
    apt:
      pkg:
      - curl
      - openssh-server
      - ca-certificates
      - tzdata
      - perl
      - postfix
      - net-tools
      - postgresql-client
      - tmux
      state: present
      update_cache: yes
  - name: get the gitlab installer
    get_url:
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
      dest: /tmp/script.deb.sh
  - name: prepare to install gitlab
    command: bash /tmp/script.deb.sh
  - name: install gitlab
    apt:
      name: gitlab-ee
      state: present
  - name: install tmux
    copy:
      src: files/tmux.conf
      dest: /home/vagrant/.tmux.conf
      owner: vagrant
      group: vagrant
      mode: '0644'
  - name: automatic tmux
    lineinfile:
      path: /home/vagrant/.bashrc
      line: tmux new-session -A -s dev
      create: yes
